server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservicecloud-user   #微服务的名称

mybatis:
  type-aliases-package: com.qqtwo.pojo

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    ip-address: 127.0.0.1
    instance-id: microservicecloud-user8003  #自定义服务实例名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: MyFirstSpringCloud-microservicecloud
  company.name: www.qqtwo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
